apiVersion: v1
kind: Pod
metadata:
  name: prom
  labels:
    name: prom
spec:
  containers:
  - name: prometheus
    image: prom/prometheus
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
    ports:
      - hostPort: 9090