apiVersion: v1
kind: Namespace
metadata:
  name: library-app
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: library-app
type: Opaque
stringData:
  password: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configuration
  namespace: library-app
data:
  mysqld.cnf: |
    [mysqld]
    pid-file	            = /var/run/mysqld/mysqld.pid
    socket		            = /var/run/mysqld/mysqld.sock
    # Where the database files are stored inside the container
    datadir		            = /var/lib/mysql

    # My application special configuration
    max_allowed_packet          = 32M
    sql-mode                    = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'
    
    # Accept connections from any IP address
    bind-address	            = 0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: library-app
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-config
          mountPath: "/etc/mysql/mysql.conf.d/"
          readOnly: true
      volumes:
      - name: mysql-config
        configMap:
          name: app-configuration
          items:
          - key: "mysqld.cnf"
            path: "mysqld.cnf"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: library-app
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306