apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: goapi
  name: goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: goapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: goapi
    spec:
      containers:
        - image: gsdockit/gsgoapi:latest
          name: goapi
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
