apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
spec:
  selector:
    matchLabels:
      app: goapi
  replicas: 2
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
      - name: goapi
        image: gsdockit/gsgoapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
