apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
spec:
  selector:
    matchLabels:
      app: mysql-client
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - name: mysql-client
        image: mysql:5.7
