apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: proxyserver
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080


