apiVersion: v1
kind: Pod
metadata:
  name: init-demo-pod
  labels:
    tier: frontend
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx:1.21-alpine
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      readinessProbe:
        exec:
          command:
          - if [ -f /usr/share/nginx/html/index.html ] ; then echo "file exist" ; fi
        initialDelaySeconds: 30
        periodSeconds: 5
  # These containers are run during pod initialization
  initContainers:
    - name: install
      image: busybox
      command:
        - sleep 
        - "30"
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://info.cern.ch
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}
