apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer # In case of lb, nodeport allocation should be automatic, if type=nodeport then we can add customised port
  ports:
  - port: 80 
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: goapi-svc
  labels:
    app: goapi
spec:
  type: NodePort # In case of lb, nodeport allocation should be automatic, if type=nodeport then we can add customised port
  ports:
  - port: 4000
  selector:
    app: goapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
spec:
  selector:
    matchLabels:
      app: goapi
  replicas: 1
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
      - name: goapi
        image: gsdockit/gsgoapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
